version: '3.8'

services:
  batpong:
    image: batpong
    container_name: Batpong
    build:
      context: containers/batpong
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - SQL_NAME=${SQL_NAME}
      - SQL_USER=${SQL_USER}
      - SQL_PWD=${SQL_PASSWORD}
      - SQL_HOST=${SQL_HOST}
      - SQL_PORT=${SQL_PORT}
    depends_on:
      - PostgreSQL
  
  PostgreSQL:
    container_name : PostgreSQL
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${SQL_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
  
volumes:
  postgres_data:

networks:
    ft_transcendence:
        driver: bridge